openapi: "3.0.0"
info:
  title: Lazychef
  version: 1.0.0
  description: Lazychef API
paths:
#####  ##### UserService #####  #####
  /users/{userId}:
    get:
      operationId: getUserDetails
      description: Get user details
      parameters:
        - in: path
          name: userId
          description: The ID of the specific user for which you want details.
          example: 1
          schema:
            type: string
          required: true
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'
        '404':
          description: User with this id was not found.
          content:
            application/json:
              schema:
                type: string


#####  ##### BoardService #####  #####

  /boards:
    post:
      operationId: createBoard
      description: Create board
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Board"
      responses:
        "201":
          description: Board created
          content:
            application/json:
              schema:
                type: string

  /boards/{boardId}:
    get:
      operationId: getBoardDetails
      description: Get board details
      parameters:
        - in: path
          name: boardId
          description: The ID of the specific board for which you want details
          example: 32355082-8fcf-422c-be53-fd7d0c478c86
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Board details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardDetails'
        '404':
          description: Board with this id was not found
          content:
            application/json:
              schema:
                type: string

  /boards/{boardId}/members:
    post:
      operationId: addBoardMembers
      description: Add board members
      parameters:
        - in: path
          name: boardId
          description: The ID of the specific board for which you want to get members
          example: 32355082-8fcf-422c-be53-fd7d0c478c86
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        "201":
          description: Members added
          content:
            application/json:
              schema:
                type: string
    get:
      operationId: getBoardMembers
      description: Get board members
      parameters:
        - in: path
          name: boardId
          description: The ID of the specific board for which you want to get members
          example: 32355082-8fcf-422c-be53-fd7d0c478c86
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Board members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDetails'
        '404':
          description: Board with this id was not found
          content:
            application/json:
              schema:
                type: string

  /boards/{boardId}/members/{memberId}:
    delete:
      operationId: deleteMember
      description: Delete member from board members
      parameters:
        - in: path
          name: boardId
          description: The ID of the specific board from which you want to delete member
          example: 32355082-8fcf-422c-be53-fd7d0c478c86
          schema:
            type: string
          required: true
        - in: path
          name: memberId
          description: The ID of the specific member which you want to delete from board members
          example: 32355082-8fcf-422c-be53-fd7d0c478c86
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Task deleted
          content:
            application/json:
              schema:
                type: string


#####  ##### TaskService #####  #####
  /tasks:
    post:
      operationId: createTask
      description: Create task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created
          content:
            application/json:
              schema:
                type: string
    patch:
      operationId: patchTask
      description: Patch some values of the task
      parameters:
        - in: path
          name: taskId
          description: The ID of the specific task for which you want details
          example: 32355082-8fcf-422c-be53-fd7d0c478c86
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskDetails"
      responses:
        '200':
          description: Task has been patched
          content:
            application/json:
              schema:
                type: string
    get:
      operationId: getBoardTasks
      description: Get all tasks assigned to board
      parameters:
        - in: query
          name: boardId
          description: The ID of the specific board for which you want details
          example: '32355082-8ccf-422c-be53-fd7d0c478c86'
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Board tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskDetails'
        '404':
          description: Board with this id was not found
          content:
            application/json:
              schema:
                type: string

  /tasks/{taskId}:
    get:
      operationId: getTask
      description: Get task
      parameters:
        - in: path
          name: taskId
          description: The ID of the specific task for which you want details
          example: 32355082-8fcf-422c-be53-fd7d0c478c86
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDetails'
        '404':
          description: Task with this id was not found
          content:
            application/json:
              schema:
                type: string

    delete:
      operationId: deleteTask
      description: Delete task
      parameters:
        - in: path
          name: taskId
          description: The ID of the specific task which you want to delete
          example: 32355082-8fcf-422c-be53-fd7d0c478c86
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Task deleted
          content:
            application/json:
              schema:
                type: string


components:
  schemas:
#####  ##### UserService #####  #####
    User:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    UserDetails:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        surname:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - surname
        - email

#####  ##### BoardService #####  #####
    Board:
      type: object
      properties:
        boardName:
          type: string
        ownerId:
          type: string
          example: "d0bf912f-3ca2-4b8c-8953-8d8b137a3084"

    BoardDetails:
      type: object
      properties:
        boardId:
          type: string
        boardName:
          type: string
        ownerId:
          type: string
        boardMembers:
          type: array
          items:
            $ref: '#/components/schemas/UserDetails'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskDetails'


#####  ##### TaskService #####  #####
    TaskStatus:
      type: string
      enum:
        - TODO
        - DOING
        - ON_HOLD
        - DONE
    Task:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        taskStatus:
          $ref: '#/components/schemas/TaskStatus'
        reporterId:
          type: string
          example: 'e4114b4e-0296-44e3-9958-099b2abf254b'
        assigneeId:
          type: string
          example: '250e59da-f641-432d-8a6a-4fde276dd667'
        boardId:
          type: string
          example: '32355082-8ccf-422c-be53-fd7d0c478c86'
    TaskDetails:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        taskStatus:
          $ref: '#/components/schemas/TaskStatus'
        reporterId:
          type: string
        assigneeId:
          type: string
        boardId:
          type: string
        createdAt:
          type: string
          format: date-time
          example: "2021-01-30T08:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2021-01-30T08:30:00Z"
